<?php

namespace Database\Seeders;

use App\Models\DestinasiWisata;
use Illuminate\Database\Seeder;

class DestinasiWisataSeeder extends Seeder
{
    public function run(): void
    {
        $destinasis = [
            [
                'nama'               => 'Taman Mangrove Bontang',
                'slug'               => 'taman-mangrove-bontang',
                'deskripsi'          => 'Kawasan konservasi mangrove terbesar di Bontang dengan jalur tracking kayu dan spot foto menarik. Cocok untuk wisata edukasi lingkungan dan birdwatching.',
                'alamat'             => 'Jl. Mangrove, Bontang Kuala, Kota Bontang',
                'latitude'           => 0.1650,
                'longitude'          => 117.5100,
                'kategori'           => 'alam',
                'thumbnail'          => null,
                'images'             => ['mangrove-1.jpg', 'mangrove-2.jpg', 'mangrove-3.jpg'],
                'jam_buka'           => '07:00',
                'jam_tutup'          => '17:00',
                'hari_operasional'   => ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu'],
                'harga_tiket'        => 10000,
                'harga_tiket_asing'  => 50000,
                'fasilitas_wisata'   => ['Parkir', 'Toilet', 'Mushola', 'Tracking Kayu', 'Spot Foto', 'Gazebo'],
                'kontak'             => '08115552001',
                'website'            => null,
                'is_ticketed'        => true,
                'is_active'          => true,
                'total_pengunjung'   => 15420,
            ],
            [
                'nama'               => 'Pantai Marina Bontang',
                'slug'               => 'pantai-marina-bontang',
                'deskripsi'          => 'Pantai pasir putih yang indah di pesisir Bontang dengan pemandangan laut Selat Makassar. Terdapat area bermain anak, gazebo, dan warung kuliner lokal.',
                'alamat'             => 'Jl. Pantai Marina, Loktuan, Kota Bontang',
                'latitude'           => 0.1800,
                'longitude'          => 117.5250,
                'kategori'           => 'bahari',
                'thumbnail'          => null,
                'images'             => ['marina-1.jpg', 'marina-2.jpg'],
                'jam_buka'           => '06:00',
                'jam_tutup'          => '18:00',
                'hari_operasional'   => ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu'],
                'harga_tiket'        => 5000,
                'harga_tiket_asing'  => 25000,
                'fasilitas_wisata'   => ['Parkir', 'Toilet', 'Mushola', 'Gazebo', 'Warung Makan', 'Area Bermain Anak'],
                'kontak'             => '08115552002',
                'website'            => null,
                'is_ticketed'        => true,
                'is_active'          => true,
                'total_pengunjung'   => 28750,
            ],
            [
                'nama'               => 'Masjid Baitul Muttaqien Agung Bontang',
                'slug'               => 'masjid-baitul-muttaqien-bontang',
                'deskripsi'          => 'Masjid agung Kota Bontang yang menjadi ikon religi kota. Arsitektur megah dengan ornamen khas Kalimantan.',
                'alamat'             => 'Jl. Jend. Sudirman, Bontang Baru, Kota Bontang',
                'latitude'           => 0.1280,
                'longitude'          => 117.4870,
                'kategori'           => 'religi',
                'thumbnail'          => null,
                'images'             => ['masjid-1.jpg'],
                'jam_buka'           => '04:00',
                'jam_tutup'          => '22:00',
                'hari_operasional'   => ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu'],
                'harga_tiket'        => 0,
                'harga_tiket_asing'  => 0,
                'fasilitas_wisata'   => ['Parkir', 'Toilet', 'Tempat Wudhu'],
                'kontak'             => null,
                'website'            => null,
                'is_ticketed'        => false,
                'is_active'          => true,
                'total_pengunjung'   => 45000,
            ],
            [
                'nama'               => 'Kampung Wisata Bontang Kuala',
                'slug'               => 'kampung-wisata-bontang-kuala',
                'deskripsi'          => 'Perkampungan nelayan di atas air yang menjadi destinasi wisata budaya bahari. Menawarkan pengalaman kehidupan nelayan dan kuliner laut segar.',
                'alamat'             => 'Bontang Kuala, Kota Bontang',
                'latitude'           => 0.1700,
                'longitude'          => 117.5080,
                'kategori'           => 'budaya',
                'thumbnail'          => null,
                'images'             => ['bontang-kuala-1.jpg', 'bontang-kuala-2.jpg', 'bontang-kuala-3.jpg'],
                'jam_buka'           => '08:00',
                'jam_tutup'          => '17:00',
                'hari_operasional'   => ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu'],
                'harga_tiket'        => 15000,
                'harga_tiket_asing'  => 75000,
                'fasilitas_wisata'   => ['Parkir', 'Perahu Wisata', 'Kuliner Laut', 'Spot Foto', 'Pemandu Wisata'],
                'kontak'             => '08115552003',
                'website'            => 'https://bontangkuala.id',
                'is_ticketed'        => true,
                'is_active'          => true,
                'total_pengunjung'   => 32100,
            ],
            [
                'nama'               => 'Taman Kota Bontang',
                'slug'               => 'taman-kota-bontang',
                'deskripsi'          => 'Taman kota modern dengan jogging track, taman bermain anak, dan area olahraga outdoor. Tempat favorit warga untuk rekreasi santai.',
                'alamat'             => 'Jl. Gatot Subroto, Bontang Baru, Kota Bontang',
                'latitude'           => 0.1260,
                'longitude'          => 117.4900,
                'kategori'           => 'buatan',
                'thumbnail'          => null,
                'images'             => ['taman-kota-1.jpg'],
                'jam_buka'           => '05:00',
                'jam_tutup'          => '22:00',
                'hari_operasional'   => ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu'],
                'harga_tiket'        => 0,
                'harga_tiket_asing'  => 0,
                'fasilitas_wisata'   => ['Parkir', 'Toilet', 'Jogging Track', 'Playground', 'WiFi Gratis'],
                'kontak'             => null,
                'website'            => null,
                'is_ticketed'        => false,
                'is_active'          => true,
                'total_pengunjung'   => 67800,
            ],
            [
                'nama'               => 'Pusat Kuliner Bontang',
                'slug'               => 'pusat-kuliner-bontang',
                'deskripsi'          => 'Pusat jajanan dan kuliner khas Bontang yang menyajikan hidangan laut segar, nasi kuning, soto Banjar, dan makanan khas Kaltim lainnya.',
                'alamat'             => 'Jl. Ahmad Yani No. 25, Bontang Selatan',
                'latitude'           => 0.1190,
                'longitude'          => 117.4730,
                'kategori'           => 'kuliner',
                'thumbnail'          => null,
                'images'             => ['kuliner-1.jpg', 'kuliner-2.jpg'],
                'jam_buka'           => '10:00',
                'jam_tutup'          => '22:00',
                'hari_operasional'   => ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu'],
                'harga_tiket'        => 0,
                'harga_tiket_asing'  => 0,
                'fasilitas_wisata'   => ['Parkir', 'Toilet', 'Area Makan Outdoor', 'Live Music'],
                'kontak'             => '08115552004',
                'website'            => null,
                'is_ticketed'        => false,
                'is_active'          => true,
                'total_pengunjung'   => 89200,
            ],
        ];

        foreach ($destinasis as $dest) {
            DestinasiWisata::create($dest);
        }
    }
}
