<?php

namespace Database\Seeders;

use App\Models\KatalogProduk;
use App\Models\Subsektor;
use App\Models\User;
use Illuminate\Database\Seeder;

class KatalogProdukSeeder extends Seeder
{
    public function run(): void
    {
        $masyarakat = User::where('role', 'masyarakat')->get();
        $subsektors = Subsektor::all()->keyBy('name');

        if ($subsektors->isEmpty()) {
            return;
        }

        $produks = [
            [
                'nama_produk'   => 'Batik Motif Mangrove Bontang',
                'slug'          => 'batik-motif-mangrove-bontang',
                'deskripsi'     => 'Batik tulis khas Bontang dengan motif mangrove dan flora pesisir Kalimantan Timur. Dibuat dengan pewarna alami.',
                'harga_mulai'   => 250000,
                'harga_sampai'  => 1500000,
                'kategori'      => 'batik',
                'subsektor_id'  => $subsektors->get('Kriya')?->id,
                'pemilik_id'    => $masyarakat->get(0)?->id,
                'nama_usaha'    => 'Batik Pesona Bontang',
                'thumbnail'     => null,
                'images'        => ['batik-mangrove-1.jpg', 'batik-mangrove-2.jpg'],
                'kontak'        => '08115553001',
                'whatsapp'      => '08115553001',
                'alamat'        => 'Jl. Mulawarman No. 12, Bontang Utara',
                'latitude'      => 0.1350,
                'longitude'     => 117.4920,
                'is_verified'   => true,
                'is_active'     => true,
            ],
            [
                'nama_produk'   => 'Amplang Ikan Khas Bontang',
                'slug'          => 'amplang-ikan-khas-bontang',
                'deskripsi'     => 'Kerupuk amplang dari ikan pipih segar. Renyah, gurih, dan menjadi oleh-oleh favorit wisatawan.',
                'harga_mulai'   => 25000,
                'harga_sampai'  => 75000,
                'kategori'      => 'kuliner',
                'subsektor_id'  => $subsektors->get('Kuliner')?->id,
                'pemilik_id'    => $masyarakat->get(1)?->id ?? $masyarakat->get(0)?->id,
                'nama_usaha'    => 'UD Amplang Mama Niar',
                'thumbnail'     => null,
                'images'        => ['amplang-1.jpg'],
                'kontak'        => '08115553002',
                'whatsapp'      => '08115553002',
                'alamat'        => 'Jl. Bontang Kuala No. 8',
                'latitude'      => 0.1670,
                'longitude'     => 117.5090,
                'is_verified'   => true,
                'is_active'     => true,
            ],
            [
                'nama_produk'   => 'Tas Rajut Etnik Dayak',
                'slug'          => 'tas-rajut-etnik-dayak',
                'deskripsi'     => 'Tas rajut handmade dengan motif etnik Dayak Kalimantan. Bahan benang katun premium, kokoh dan fashionable.',
                'harga_mulai'   => 150000,
                'harga_sampai'  => 450000,
                'kategori'      => 'kriya',
                'subsektor_id'  => $subsektors->get('Fesyen')?->id,
                'pemilik_id'    => $masyarakat->get(0)?->id,
                'nama_usaha'    => 'Rajut Nusantara',
                'thumbnail'     => null,
                'images'        => ['tas-rajut-1.jpg', 'tas-rajut-2.jpg'],
                'kontak'        => '08115553003',
                'whatsapp'      => '08115553003',
                'alamat'        => 'Jl. Ahmad Yani No. 30, Bontang Selatan',
                'latitude'      => 0.1200,
                'longitude'     => 117.4740,
                'is_verified'   => true,
                'is_active'     => true,
            ],
            [
                'nama_produk'   => 'Lukisan Panorama Bontang Kuala',
                'slug'          => 'lukisan-panorama-bontang-kuala',
                'deskripsi'     => 'Lukisan cat minyak menggambarkan keindahan perkampungan di atas air Bontang Kuala. Karya seniman lokal.',
                'harga_mulai'   => 500000,
                'harga_sampai'  => 5000000,
                'kategori'      => 'seni_rupa',
                'subsektor_id'  => $subsektors->get('Seni Rupa')?->id,
                'pemilik_id'    => null,
                'nama_usaha'    => 'Galeri Seni Bontang',
                'thumbnail'     => null,
                'images'        => ['lukisan-1.jpg'],
                'kontak'        => '08115553004',
                'whatsapp'      => '08115553004',
                'alamat'        => 'Jl. Ir. Sutami No. 22, Bontang',
                'latitude'      => 0.1160,
                'longitude'     => 117.4790,
                'is_verified'   => false,
                'is_active'     => true,
            ],
            [
                'nama_produk'   => 'Kopi Robusta Bontang',
                'slug'          => 'kopi-robusta-bontang',
                'deskripsi'     => 'Kopi robusta pilihan dari perkebunan sekitar Bontang. Disangrai medium-dark, aroma kuat dan rasa khas.',
                'harga_mulai'   => 50000,
                'harga_sampai'  => 150000,
                'kategori'      => 'kuliner',
                'subsektor_id'  => $subsektors->get('Kuliner')?->id,
                'pemilik_id'    => $masyarakat->get(1)?->id ?? $masyarakat->get(0)?->id,
                'nama_usaha'    => 'Kopi Kaltim Roastery',
                'thumbnail'     => null,
                'images'        => ['kopi-1.jpg', 'kopi-2.jpg'],
                'kontak'        => '08115553005',
                'whatsapp'      => '08115553005',
                'alamat'        => 'Jl. KH Ahmad Dahlan No. 15, Bontang',
                'latitude'      => 0.1300,
                'longitude'     => 117.5000,
                'is_verified'   => true,
                'is_active'     => true,
            ],
            [
                'nama_produk'   => 'Kaos Desain Bontang Heritage',
                'slug'          => 'kaos-desain-bontang-heritage',
                'deskripsi'     => 'Kaos dengan desain ilustrasi ikon-ikon Bontang. Bahan cotton combed 30s, sablon DTF berkualitas tinggi.',
                'harga_mulai'   => 85000,
                'harga_sampai'  => 150000,
                'kategori'      => 'fashion',
                'subsektor_id'  => $subsektors->get('Fesyen')?->id,
                'pemilik_id'    => null,
                'nama_usaha'    => 'Bontang Apparel',
                'thumbnail'     => null,
                'images'        => ['kaos-1.jpg', 'kaos-2.jpg', 'kaos-3.jpg'],
                'kontak'        => '08115553006',
                'whatsapp'      => '08115553006',
                'alamat'        => 'Jl. Letjen S. Parman No. 10, Bontang',
                'latitude'      => 0.1220,
                'longitude'     => 117.4850,
                'is_verified'   => false,
                'is_active'     => true,
            ],
            [
                'nama_produk'   => 'Miniatur Rumah Adat Lamin',
                'slug'          => 'miniatur-rumah-adat-lamin',
                'deskripsi'     => 'Kerajinan miniatur rumah adat Lamin dari kayu ulin. Cocok untuk souvenir dan koleksi.',
                'harga_mulai'   => 200000,
                'harga_sampai'  => 800000,
                'kategori'      => 'kriya',
                'subsektor_id'  => $subsektors->get('Kriya')?->id,
                'pemilik_id'    => $masyarakat->get(0)?->id,
                'nama_usaha'    => 'Kriya Kayu Bontang',
                'thumbnail'     => null,
                'images'        => ['lamin-1.jpg'],
                'kontak'        => '08115553007',
                'whatsapp'      => '08115553007',
                'alamat'        => 'Jl. Moh. Roem No. 5, Bontang Utara',
                'latitude'      => 0.1320,
                'longitude'     => 117.4940,
                'is_verified'   => true,
                'is_active'     => true,
            ],
            [
                'nama_produk'   => 'Foto Cetak Premium Pesisir Bontang',
                'slug'          => 'foto-cetak-premium-pesisir-bontang',
                'deskripsi'     => 'Koleksi foto premium keindahan pesisir Bontang, dicetak di atas kanvas dengan bingkai kayu.',
                'harga_mulai'   => 300000,
                'harga_sampai'  => 1200000,
                'kategori'      => 'fotografi',
                'subsektor_id'  => $subsektors->get('Fotografi')?->id,
                'pemilik_id'    => null,
                'nama_usaha'    => 'Bontang Lens Studio',
                'thumbnail'     => null,
                'images'        => ['foto-cetak-1.jpg'],
                'kontak'        => '08115553008',
                'whatsapp'      => '08115553008',
                'alamat'        => 'Jl. Bessai Berinta No. 7, Bontang',
                'latitude'      => 0.1270,
                'longitude'     => 117.4880,
                'is_verified'   => false,
                'is_active'     => true,
            ],
        ];

        foreach ($produks as $produk) {
            KatalogProduk::create($produk);
        }
    }
}
