<?php

namespace Database\Seeders;

use App\Models\PelakuEkraf;
use App\Models\Subsektor;
use App\Models\User;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Str;

class PelakuEkrafSeeder extends Seeder
{
    /**
     * Helper: cari subsektor berdasarkan keyword pada kolom `name`.
     */
    private function findSubsektor($subsektors, string $keyword): ?int
    {
        $sub = $subsektors->filter(
            fn ($s) => str_contains(strtolower($s->name), strtolower($keyword))
        )->first();

        return $sub?->id ?? $subsektors->first()?->id;
    }

    public function run(): void
    {
        $subsektors = Subsektor::all();
        if ($subsektors->isEmpty()) {
            return;
        }

        $user   = User::first();
        $userId = $user?->id;

        $items = [
            // ── 1  Kriya ────────────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Ibu Fatimah',
                'slug'               => 'ibu-fatimah',
                'nik'                => '6474024501800001',
                'nama_usaha'         => 'Batik Bontang Pesisir',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Kriya'),
                'deskripsi_usaha'    => 'Usaha batik tulis dan cap dengan motif khas pesisir Bontang seperti motif mangrove, lumba-lumba, dan gelombang laut.',
                'alamat'             => 'Jl. Pelabuhan Loktuan No. 12',
                'kelurahan'          => 'Loktuan',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1234567,
                'longitude'          => 117.4567890,
                'no_telp'            => '08115591001',
                'email'              => 'batikpesisir@mail.com',
                'website'            => null,
                'sosial_media'       => ['instagram' => '@batikpesisirbontang'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2015,
                'jumlah_karyawan'    => 8,
                'skala_usaha'        => 'kecil',
                'omzet_tahunan'      => 120000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(30),
                'catatan_verifikasi' => 'Data lengkap dan usaha aktif berproduksi.',
            ],

            // ── 2  Kuliner ──────────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Pak Hendra Wijaya',
                'slug'               => 'pak-hendra-wijaya',
                'nik'                => '6474012003850002',
                'nama_usaha'         => 'Bontang Coffee Roastery',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Kuliner'),
                'deskripsi_usaha'    => 'Roastery kopi lokal Kalimantan Timur dengan spesialisasi single origin dari Berau dan Mahakam.',
                'alamat'             => 'Jl. MT Haryono No. 55',
                'kelurahan'          => 'Tanjung Laut',
                'kecamatan'          => 'Bontang Selatan',
                'latitude'           => 0.0987654,
                'longitude'          => 117.4321098,
                'no_telp'            => '08115591002',
                'email'              => 'bontangcoffee@mail.com',
                'website'            => 'https://bontangcoffee.id',
                'sosial_media'       => ['instagram' => '@bontangcoffee', 'tiktok' => '@bontangcoffee'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2019,
                'jumlah_karyawan'    => 5,
                'skala_usaha'        => 'mikro',
                'omzet_tahunan'      => 80000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(20),
                'catatan_verifikasi' => 'Produk berkualitas, sudah memiliki PIRT.',
            ],

            // ── 3  Fesyen ───────────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Diana Permata',
                'slug'               => 'diana-permata',
                'nik'                => '6474025506900003',
                'nama_usaha'         => 'Bontang Fashion Studio',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Fesyen'),
                'deskripsi_usaha'    => 'Studio desain fashion lokal yang mengkombinasikan kain tradisional Dayak dengan desain modern kontemporer.',
                'alamat'             => 'Ruko Bontang Lestari Blok A-5',
                'kelurahan'          => 'Bontang Lestari',
                'kecamatan'          => 'Bontang Selatan',
                'latitude'           => null,
                'longitude'          => null,
                'no_telp'            => '08115591003',
                'email'              => 'dianafashion@mail.com',
                'website'            => null,
                'sosial_media'       => ['instagram' => '@bontangfashionstudio'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2021,
                'jumlah_karyawan'    => 3,
                'skala_usaha'        => 'mikro',
                'omzet_tahunan'      => 50000000,
                'status'             => 'pending',
                'verified_by'        => null,
                'verified_at'        => null,
                'catatan_verifikasi' => null,
            ],

            // ── 4  Aplikasi / Digital ───────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Agus Salim',
                'slug'               => 'agus-salim',
                'nik'                => '6474011508880004',
                'nama_usaha'         => 'Bontang Digital Creative',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Aplikasi'),
                'deskripsi_usaha'    => 'Jasa desain grafis, video editing, dan pembuatan konten digital untuk UMKM dan instansi pemerintah.',
                'alamat'             => 'Jl. Brigjend Katamso No. 20',
                'kelurahan'          => 'Gunung Elai',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1456789,
                'longitude'          => 117.4789012,
                'no_telp'            => '08115591004',
                'email'              => 'bontangdigital@mail.com',
                'website'            => 'https://bontangdigital.id',
                'sosial_media'       => ['instagram' => '@bontangdigital', 'youtube' => 'Bontang Digital'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2020,
                'jumlah_karyawan'    => 6,
                'skala_usaha'        => 'kecil',
                'omzet_tahunan'      => 200000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(15),
                'catatan_verifikasi' => 'Portfolio lengkap, sudah berbadan hukum CV.',
            ],

            // ── 5  Kuliner ──────────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Nurul Hidayah',
                'slug'               => 'nurul-hidayah',
                'nik'                => '6474022212950005',
                'nama_usaha'         => 'Kerupuk Ikan Khas Bontang',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Kuliner'),
                'deskripsi_usaha'    => 'Produksi kerupuk ikan dan amplang khas Bontang dengan resep turun-temurun. Sudah diekspor ke beberapa kota di Pulau Jawa.',
                'alamat'             => 'Jl. Nelayan No. 8, Kelurahan Tanjung Laut Indah',
                'kelurahan'          => 'Tanjung Laut Indah',
                'kecamatan'          => 'Bontang Selatan',
                'latitude'           => 0.0876543,
                'longitude'          => 117.4654321,
                'no_telp'            => '08115591005',
                'email'              => 'kerupukbontang@mail.com',
                'website'            => null,
                'sosial_media'       => ['instagram' => '@kerupukbontang', 'shopee' => 'Kerupuk Bontang'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2010,
                'jumlah_karyawan'    => 15,
                'skala_usaha'        => 'menengah',
                'omzet_tahunan'      => 500000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(60),
                'catatan_verifikasi' => 'UMKM binaan unggulan, sudah BPOM dan halal MUI.',
            ],

            // ── 6  Fotografi ────────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Rizky Pratama',
                'slug'               => 'rizky-pratama',
                'nik'                => '6474011207920006',
                'nama_usaha'         => 'Bontang Lens Photography',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Fotografi'),
                'deskripsi_usaha'    => 'Studio fotografi profesional untuk wedding, prewedding, produk komersial, dan dokumentasi event pemerintah daerah.',
                'alamat'             => 'Jl. AW Syahrani No. 33',
                'kelurahan'          => 'Api-Api',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1345678,
                'longitude'          => 117.4890123,
                'no_telp'            => '08115591006',
                'email'              => 'bontanglens@mail.com',
                'website'            => 'https://bontanglens.com',
                'sosial_media'       => ['instagram' => '@bontanglens', 'facebook' => 'Bontang Lens'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2017,
                'jumlah_karyawan'    => 4,
                'skala_usaha'        => 'mikro',
                'omzet_tahunan'      => 150000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(10),
                'catatan_verifikasi' => 'Portfolio memuaskan, aktif di komunitas fotografi.',
            ],

            // ── 7  Musik ────────────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Bayu Aditya',
                'slug'               => 'bayu-aditya',
                'nik'                => '6474010504930007',
                'nama_usaha'         => 'Harmoni Studio Bontang',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Musik'),
                'deskripsi_usaha'    => 'Studio rekaman musik, jasa aransemen, dan produksi jingle untuk iklan dan branding UMKM lokal.',
                'alamat'             => 'Jl. Letjend S. Parman No. 18',
                'kelurahan'          => 'Belimbing',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1567890,
                'longitude'          => 117.4567800,
                'no_telp'            => '08115591007',
                'email'              => 'harmonistudio@mail.com',
                'website'            => null,
                'sosial_media'       => ['instagram' => '@harmonibontang', 'youtube' => 'Harmoni Studio'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2018,
                'jumlah_karyawan'    => 3,
                'skala_usaha'        => 'mikro',
                'omzet_tahunan'      => 90000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(45),
                'catatan_verifikasi' => 'Peralatan lengkap, sudah melayani klien korporat.',
            ],

            // ── 8  Desain Komunikasi Visual ─────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Siti Aisyah',
                'slug'               => 'siti-aisyah',
                'nik'                => '6474026708970008',
                'nama_usaha'         => 'Kreativa Design Studio',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Desain Komunikasi Visual'),
                'deskripsi_usaha'    => 'Jasa desain branding, logo, kemasan produk UMKM, dan percetakan digital.',
                'alamat'             => 'Jl. Slamet Riyadi No. 45',
                'kelurahan'          => 'Kanaan',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1289012,
                'longitude'          => 117.4912345,
                'no_telp'            => '08115591008',
                'email'              => 'kreativadesign@mail.com',
                'website'            => 'https://kreativadesign.id',
                'sosial_media'       => ['instagram' => '@kreativadesign'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2022,
                'jumlah_karyawan'    => 2,
                'skala_usaha'        => 'mikro',
                'omzet_tahunan'      => 60000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(7),
                'catatan_verifikasi' => 'Pelaku muda potensial, portofolio menarik.',
            ],

            // ── 9  Seni Pertunjukan ─────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Pak Daeng Maulana',
                'slug'               => 'pak-daeng-maulana',
                'nik'                => '6474011011780009',
                'nama_usaha'         => 'Sanggar Seni Pesut Mahakam',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Seni Pertunjukan'),
                'deskripsi_usaha'    => 'Sanggar seni tari dan musik tradisional Kutai, Dayak, dan Bugis untuk pertunjukan budaya dan event pariwisata.',
                'alamat'             => 'Jl. Imam Bonjol No. 7',
                'kelurahan'          => 'Berbas Pantai',
                'kecamatan'          => 'Bontang Selatan',
                'latitude'           => 0.0765432,
                'longitude'          => 117.4543210,
                'no_telp'            => '08115591009',
                'email'              => 'sanggarpesut@mail.com',
                'website'            => null,
                'sosial_media'       => ['instagram' => '@sanggarpesutmahakam'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2008,
                'jumlah_karyawan'    => 20,
                'skala_usaha'        => 'kecil',
                'omzet_tahunan'      => 180000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(90),
                'catatan_verifikasi' => 'Sanggar aktif, rutin tampil di event Pemkot Bontang.',
            ],

            // ── 10  Film, Animasi & Video ───────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Andi Firmansyah',
                'slug'               => 'andi-firmansyah',
                'nik'                => '6474012508960010',
                'nama_usaha'         => 'Bontang Motion Pictures',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Film'),
                'deskripsi_usaha'    => 'Produksi video company profile, video promosi wisata, dokumenter, dan konten media sosial untuk instansi dan UMKM.',
                'alamat'             => 'Jl. DI Panjaitan No. 22',
                'kelurahan'          => 'Gunung Elai',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1398765,
                'longitude'          => 117.4801234,
                'no_telp'            => '08115591010',
                'email'              => 'bontangmotion@mail.com',
                'website'            => 'https://bontangmotion.id',
                'sosial_media'       => ['instagram' => '@bontangmotion', 'youtube' => 'Bontang Motion Pictures'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2019,
                'jumlah_karyawan'    => 7,
                'skala_usaha'        => 'kecil',
                'omzet_tahunan'      => 250000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(25),
                'catatan_verifikasi' => 'Karya berkualitas, sudah menangani proyek APBD.',
            ],

            // ── 11  Periklanan ──────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Rina Marlianti',
                'slug'               => 'rina-marlianti',
                'nik'                => '6474023003910011',
                'nama_usaha'         => 'Advis Media Bontang',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Periklanan'),
                'deskripsi_usaha'    => 'Agensi periklanan lokal fokus pada kampanye digital marketing, manajemen media sosial, dan branding UMKM.',
                'alamat'             => 'Jl. Ahmad Yani No. 66',
                'kelurahan'          => 'Tanjung Laut',
                'kecamatan'          => 'Bontang Selatan',
                'latitude'           => 0.0912345,
                'longitude'          => 117.4398765,
                'no_telp'            => '08115591011',
                'email'              => 'advismedia@mail.com',
                'website'            => 'https://advismedia.com',
                'sosial_media'       => ['instagram' => '@advismediabontang', 'linkedin' => 'Advis Media'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2020,
                'jumlah_karyawan'    => 4,
                'skala_usaha'        => 'mikro',
                'omzet_tahunan'      => 110000000,
                'status'             => 'pending',
                'verified_by'        => null,
                'verified_at'        => null,
                'catatan_verifikasi' => null,
            ],

            // ── 12  Seni Rupa ───────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Wahyu Setiawan',
                'slug'               => 'wahyu-setiawan',
                'nik'                => '6474011706850012',
                'nama_usaha'         => 'Galeri Seni Borneo Art',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Seni Rupa'),
                'deskripsi_usaha'    => 'Galeri lukisan dan patung bertema alam Kalimantan. Menjual karya seni asli dan menerima pesanan mural.',
                'alamat'             => 'Jl. Kapten Piere Tendean No. 10',
                'kelurahan'          => 'Api-Api',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1501234,
                'longitude'          => 117.4923456,
                'no_telp'            => '08115591012',
                'email'              => 'borneoart@mail.com',
                'website'            => null,
                'sosial_media'       => ['instagram' => '@borneoartgallery'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2014,
                'jumlah_karyawan'    => 2,
                'skala_usaha'        => 'mikro',
                'omzet_tahunan'      => 70000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(50),
                'catatan_verifikasi' => 'Aktif pameran seni, karya sudah dijual ke luar kota.',
            ],

            // ── 13  Desain Produk ───────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Yusuf Ramadhan',
                'slug'               => 'yusuf-ramadhan',
                'nik'                => '6474010108990013',
                'nama_usaha'         => 'Bontang Craft Furniture',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Desain Produk'),
                'deskripsi_usaha'    => 'Bengkel furnitur custom dari kayu daur ulang dan rotan lokal dengan desain minimalis modern.',
                'alamat'             => 'Jl. Mulawarman No. 88',
                'kelurahan'          => 'Loktuan',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1178901,
                'longitude'          => 117.4601234,
                'no_telp'            => '08115591013',
                'email'              => 'bontangcraft@mail.com',
                'website'            => null,
                'sosial_media'       => ['instagram' => '@bontangcraftfurniture', 'tokopedia' => 'Bontang Craft'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2016,
                'jumlah_karyawan'    => 10,
                'skala_usaha'        => 'kecil',
                'omzet_tahunan'      => 300000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(35),
                'catatan_verifikasi' => 'Produk berkualitas, sudah supply ke hotel dan resort.',
            ],

            // ── 14  Arsitektur ──────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Ir. Hesti Kurniawati',
                'slug'               => 'ir-hesti-kurniawati',
                'nik'                => '6474024409870014',
                'nama_usaha'         => 'Arsitek Pesisir Bontang',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Arsitektur'),
                'deskripsi_usaha'    => 'Konsultan arsitektur yang berfokus pada desain bangunan ramah lingkungan dan pembangunan kawasan pesisir.',
                'alamat'             => 'Jl. Siaga No. 15',
                'kelurahan'          => 'Kanaan',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1423456,
                'longitude'          => 117.4756789,
                'no_telp'            => '08115591014',
                'email'              => 'arsitekpesisir@mail.com',
                'website'            => 'https://arsitekpesisir.co.id',
                'sosial_media'       => ['instagram' => '@arsitekpesisir'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2012,
                'jumlah_karyawan'    => 8,
                'skala_usaha'        => 'kecil',
                'omzet_tahunan'      => 400000000,
                'status'             => 'terverifikasi',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(40),
                'catatan_verifikasi' => 'Berpengalaman, sudah menangani proyek pemerintah.',
            ],

            // ── 15  Penerbitan ──────────────────────────
            [
                'user_id'            => $userId,
                'nama'               => 'Lestari Dewi',
                'slug'               => 'lestari-dewi',
                'nik'                => '6474026601000015',
                'nama_usaha'         => 'Penerbit Cahaya Bontang',
                'subsektor_id'       => $this->findSubsektor($subsektors, 'Penerbitan'),
                'deskripsi_usaha'    => 'Penerbitan buku cerita anak bertema kearifan lokal Kalimantan, buku panduan wisata, dan majalah komunitas.',
                'alamat'             => 'Jl. Gatot Subroto No. 30',
                'kelurahan'          => 'Belimbing',
                'kecamatan'          => 'Bontang Utara',
                'latitude'           => 0.1534567,
                'longitude'          => 117.4534567,
                'no_telp'            => '08115591015',
                'email'              => 'cahayabontang@mail.com',
                'website'            => null,
                'sosial_media'       => ['instagram' => '@penerbitmcahayabontang'],
                'foto'               => null,
                'logo_usaha'         => null,
                'tahun_mulai'        => 2023,
                'jumlah_karyawan'    => 2,
                'skala_usaha'        => 'mikro',
                'omzet_tahunan'      => 35000000,
                'status'             => 'ditolak',
                'verified_by'        => $userId,
                'verified_at'        => Carbon::now()->subDays(5),
                'catatan_verifikasi' => 'Dokumen izin usaha belum lengkap, mohon dilengkapi dan ajukan kembali.',
            ],
        ];

        foreach ($items as $item) {
            PelakuEkraf::create($item);
        }
    }
}
